export type AssetClass =
  | "forex"
  | "crypto"
  | "metals"
  | "indices"
  | "energy"
  | "shares";

export type Instrument = {
  symbol: string;
  display: string;
  name: string;
  assetClass: AssetClass;
  /** Mid price seed, late Sep 2026. */
  base: number;
  digits: number;
  pip: number;
  /** Standard account bid/ask width in price units. */
  spreadStd: number;
  /** RAW account bid/ask width in price units. */
  spreadRaw: number;
  /** Contract size per 1.00 lot. */
  contractSize: number;
  leverage: number;
  /** Annualised-ish tick volatility for the simulator. */
  vol: number;
  /** Commission USD per 1.00 lot per side on RAW. 0 = spread-only. */
  commissionRaw: number;
  hours: string;
};

export const ASSET_LABEL: Record<AssetClass, string> = {
  forex: "Forex",
  crypto: "Crypto",
  metals: "Metals",
  indices: "Indices",
  energy: "Energy",
  shares: "Shares",
};

export const INSTRUMENTS: Instrument[] = [
  // Forex majors & crosses — pip = 0.0001 except JPY 0.01
  {
    symbol: "EURUSD",
    display: "EUR/USD",
    name: "Euro / US Dollar",
    assetClass: "forex",
    base: 1.1483,
    digits: 5,
    pip: 0.0001,
    spreadStd: 0.0001,
    spreadRaw: 0.00002,
    contractSize: 100_000,
    leverage: 50,
    vol: 0.00022,
    commissionRaw: 3.5,
    hours: "24/5",
  },
  {
    symbol: "GBPUSD",
    display: "GBP/USD",
    name: "Pound / US Dollar",
    assetClass: "forex",
    base: 1.3393,
    digits: 5,
    pip: 0.0001,
    spreadStd: 0.00013,
    spreadRaw: 0.00003,
    contractSize: 100_000,
    leverage: 50,
    vol: 0.00028,
    commissionRaw: 3.5,
    hours: "24/5",
  },
  {
    symbol: "USDJPY",
    display: "USD/JPY",
    name: "US Dollar / Yen",
    assetClass: "forex",
    base: 156.85,
    digits: 3,
    pip: 0.01,
    spreadStd: 0.011,
    spreadRaw: 0.003,
    contractSize: 100_000,
    leverage: 50,
    vol: 0.0002,
    commissionRaw: 3.5,
    hours: "24/5",
  },
  {
    symbol: "USDCHF",
    display: "USD/CHF",
    name: "US Dollar / Swiss Franc",
    assetClass: "forex",
    base: 0.8218,
    digits: 5,
    pip: 0.0001,
    spreadStd: 0.00015,
    spreadRaw: 0.00004,
    contractSize: 100_000,
    leverage: 50,
    vol: 0.0002,
    commissionRaw: 3.5,
    hours: "24/5",
  },
  {
    symbol: "AUDUSD",
    display: "AUD/USD",
    name: "Aussie / US Dollar",
    assetClass: "forex",
    base: 0.7117,
    digits: 5,
    pip: 0.0001,
    spreadStd: 0.00012,
    spreadRaw: 0.00003,
    contractSize: 100_000,
    leverage: 50,
    vol: 0.00026,
    commissionRaw: 3.5,
    hours: "24/5",
  },
  {
    symbol: "USDCAD",
    display: "USD/CAD",
    name: "US Dollar / Canadian Dollar",
    assetClass: "forex",
    base: 1.4001,
    digits: 5,
    pip: 0.0001,
    spreadStd: 0.00016,
    spreadRaw: 0.00004,
    contractSize: 100_000,
    leverage: 50,
    vol: 0.00022,
    commissionRaw: 3.5,
    hours: "24/5",
  },
  {
    symbol: "NZDUSD",
    display: "NZD/USD",
    name: "Kiwi / US Dollar",
    assetClass: "forex",
    base: 0.5723,
    digits: 5,
    pip: 0.0001,
    spreadStd: 0.00016,
    spreadRaw: 0.00005,
    contractSize: 100_000,
    leverage: 50,
    vol: 0.0003,
    commissionRaw: 3.5,
    hours: "24/5",
  },
  {
    symbol: "EURGBP",
    display: "EUR/GBP",
    name: "Euro / Pound",
    assetClass: "forex",
    base: 0.8571,
    digits: 5,
    pip: 0.0001,
    spreadStd: 0.00012,
    spreadRaw: 0.00004,
    contractSize: 100_000,
    leverage: 50,
    vol: 0.00018,
    commissionRaw: 3.5,
    hours: "24/5",
  },
  {
    symbol: "EURJPY",
    display: "EUR/JPY",
    name: "Euro / Yen",
    assetClass: "forex",
    base: 180.12,
    digits: 3,
    pip: 0.01,
    spreadStd: 0.015,
    spreadRaw: 0.005,
    contractSize: 100_000,
    leverage: 50,
    vol: 0.00024,
    commissionRaw: 3.5,
    hours: "24/5",
  },
  {
    symbol: "GBPJPY",
    display: "GBP/JPY",
    name: "Pound / Yen",
    assetClass: "forex",
    base: 210.08,
    digits: 3,
    pip: 0.01,
    spreadStd: 0.02,
    spreadRaw: 0.007,
    contractSize: 100_000,
    leverage: 50,
    vol: 0.00032,
    commissionRaw: 3.5,
    hours: "24/5",
  },
  {
    symbol: "USDINR",
    display: "USD/INR",
    name: "US Dollar / Indian Rupee",
    assetClass: "forex",
    base: 88.42,
    digits: 3,
    pip: 0.01,
    spreadStd: 0.04,
    spreadRaw: 0.015,
    contractSize: 100_000,
    leverage: 20,
    vol: 0.00012,
    commissionRaw: 3.5,
    hours: "24/5",
  },
  // Crypto
  {
    symbol: "BTCUSD",
    display: "BTC/USD",
    name: "Bitcoin",
    assetClass: "crypto",
    base: 77990,
    digits: 1,
    pip: 1,
    spreadStd: 28,
    spreadRaw: 12,
    contractSize: 1,
    leverage: 5,
    vol: 0.0014,
    commissionRaw: 0,
    hours: "24/7",
  },
  {
    symbol: "ETHUSD",
    display: "ETH/USD",
    name: "Ethereum",
    assetClass: "crypto",
    base: 2505.5,
    digits: 2,
    pip: 0.1,
    spreadStd: 1.6,
    spreadRaw: 0.7,
    contractSize: 1,
    leverage: 5,
    vol: 0.0016,
    commissionRaw: 0,
    hours: "24/7",
  },
  {
    symbol: "SOLUSD",
    display: "SOL/USD",
    name: "Solana",
    assetClass: "crypto",
    base: 94.06,
    digits: 3,
    pip: 0.01,
    spreadStd: 0.08,
    spreadRaw: 0.04,
    contractSize: 1,
    leverage: 5,
    vol: 0.002,
    commissionRaw: 0,
    hours: "24/7",
  },
  {
    symbol: "XRPUSD",
    display: "XRP/USD",
    name: "XRP",
    assetClass: "crypto",
    base: 1.502,
    digits: 4,
    pip: 0.0001,
    spreadStd: 0.0024,
    spreadRaw: 0.001,
    contractSize: 1,
    leverage: 5,
    vol: 0.0022,
    commissionRaw: 0,
    hours: "24/7",
  },
  // Metals
  {
    symbol: "XAUUSD",
    display: "XAU/USD",
    name: "Spot Gold",
    assetClass: "metals",
    base: 4385.9,
    digits: 2,
    pip: 0.1,
    spreadStd: 0.32,
    spreadRaw: 0.12,
    contractSize: 100,
    leverage: 20,
    vol: 0.00045,
    commissionRaw: 0,
    hours: "7-day",
  },
  {
    symbol: "XAGUSD",
    display: "XAG/USD",
    name: "Spot Silver",
    assetClass: "metals",
    base: 66.27,
    digits: 3,
    pip: 0.01,
    spreadStd: 0.028,
    spreadRaw: 0.012,
    contractSize: 5000,
    leverage: 10,
    vol: 0.0008,
    commissionRaw: 0,
    hours: "24/5",
  },
  {
    symbol: "XPTUSD",
    display: "XPT/USD",
    name: "Spot Platinum",
    assetClass: "metals",
    base: 1808,
    digits: 2,
    pip: 0.1,
    spreadStd: 1.4,
    spreadRaw: 0.6,
    contractSize: 50,
    leverage: 10,
    vol: 0.0007,
    commissionRaw: 0,
    hours: "24/5",
  },
  // Indices
  {
    symbol: "US100",
    display: "US Tech 100",
    name: "Nasdaq 100",
    assetClass: "indices",
    base: 29522,
    digits: 1,
    pip: 1,
    spreadStd: 1.2,
    spreadRaw: 0.6,
    contractSize: 1,
    leverage: 20,
    vol: 0.00035,
    commissionRaw: 0,
    hours: "Extended",
  },
  {
    symbol: "US30",
    display: "Wall Street 30",
    name: "Dow Jones",
    assetClass: "indices",
    base: 51770,
    digits: 1,
    pip: 1,
    spreadStd: 2.2,
    spreadRaw: 1.0,
    contractSize: 1,
    leverage: 20,
    vol: 0.00028,
    commissionRaw: 0,
    hours: "Extended",
  },
  {
    symbol: "US500",
    display: "US 500",
    name: "S&P 500",
    assetClass: "indices",
    base: 7650.5,
    digits: 1,
    pip: 0.1,
    spreadStd: 0.5,
    spreadRaw: 0.25,
    contractSize: 1,
    leverage: 20,
    vol: 0.00028,
    commissionRaw: 0,
    hours: "Extended",
  },
  {
    symbol: "GER40",
    display: "Germany 40",
    name: "DAX 40",
    assetClass: "indices",
    base: 25314,
    digits: 1,
    pip: 1,
    spreadStd: 1.6,
    spreadRaw: 0.8,
    contractSize: 1,
    leverage: 20,
    vol: 0.00032,
    commissionRaw: 0,
    hours: "24/5",
  },
  {
    symbol: "UK100",
    display: "UK 100",
    name: "FTSE 100",
    assetClass: "indices",
    base: 10659,
    digits: 1,
    pip: 1,
    spreadStd: 1.4,
    spreadRaw: 0.7,
    contractSize: 1,
    leverage: 20,
    vol: 0.0003,
    commissionRaw: 0,
    hours: "24/5",
  },
  // Energy
  {
    symbol: "USOIL",
    display: "US Crude",
    name: "WTI Crude Oil",
    assetClass: "energy",
    base: 95.42,
    digits: 2,
    pip: 0.01,
    spreadStd: 0.04,
    spreadRaw: 0.02,
    contractSize: 100,
    leverage: 10,
    vol: 0.0007,
    commissionRaw: 0,
    hours: "24/5",
  },
  {
    symbol: "UKOIL",
    display: "UK Brent",
    name: "Brent Crude Oil",
    assetClass: "energy",
    base: 103.37,
    digits: 2,
    pip: 0.01,
    spreadStd: 0.04,
    spreadRaw: 0.02,
    contractSize: 100,
    leverage: 10,
    vol: 0.00065,
    commissionRaw: 0,
    hours: "24/5",
  },
  {
    symbol: "NATGAS",
    display: "Natural Gas",
    name: "US Natural Gas",
    assetClass: "energy",
    base: 2.9,
    digits: 3,
    pip: 0.001,
    spreadStd: 0.008,
    spreadRaw: 0.004,
    contractSize: 10000,
    leverage: 10,
    vol: 0.0014,
    commissionRaw: 0,
    hours: "24/5",
  },
  // Share CFDs
  {
    symbol: "NVDA",
    display: "NVDA",
    name: "NVIDIA",
    assetClass: "shares",
    base: 178.4,
    digits: 2,
    pip: 0.01,
    spreadStd: 0.06,
    spreadRaw: 0.04,
    contractSize: 1,
    leverage: 5,
    vol: 0.0009,
    commissionRaw: 0,
    hours: "Extended",
  },
  {
    symbol: "TSLA",
    display: "TSLA",
    name: "Tesla",
    assetClass: "shares",
    base: 246.8,
    digits: 2,
    pip: 0.01,
    spreadStd: 0.08,
    spreadRaw: 0.05,
    contractSize: 1,
    leverage: 5,
    vol: 0.0012,
    commissionRaw: 0,
    hours: "Extended",
  },
  {
    symbol: "AAPL",
    display: "AAPL",
    name: "Apple",
    assetClass: "shares",
    base: 232.15,
    digits: 2,
    pip: 0.01,
    spreadStd: 0.04,
    spreadRaw: 0.03,
    contractSize: 1,
    leverage: 5,
    vol: 0.00055,
    commissionRaw: 0,
    hours: "Extended",
  },
  {
    symbol: "MSFT",
    display: "MSFT",
    name: "Microsoft",
    assetClass: "shares",
    base: 428.6,
    digits: 2,
    pip: 0.01,
    spreadStd: 0.06,
    spreadRaw: 0.04,
    contractSize: 1,
    leverage: 5,
    vol: 0.0005,
    commissionRaw: 0,
    hours: "Extended",
  },
  {
    symbol: "AMZN",
    display: "AMZN",
    name: "Amazon",
    assetClass: "shares",
    base: 221.3,
    digits: 2,
    pip: 0.01,
    spreadStd: 0.05,
    spreadRaw: 0.03,
    contractSize: 1,
    leverage: 5,
    vol: 0.00065,
    commissionRaw: 0,
    hours: "Extended",
  },
  {
    symbol: "GOOGL",
    display: "GOOGL",
    name: "Alphabet",
    assetClass: "shares",
    base: 186.9,
    digits: 2,
    pip: 0.01,
    spreadStd: 0.05,
    spreadRaw: 0.03,
    contractSize: 1,
    leverage: 5,
    vol: 0.0006,
    commissionRaw: 0,
    hours: "Extended",
  },
];

export const INSTRUMENT_MAP = new Map(INSTRUMENTS.map((i) => [i.symbol, i]));

export function getInstrument(symbol: string): Instrument {
  const inst = INSTRUMENT_MAP.get(symbol);
  if (!inst) throw new Error(`Unknown symbol ${symbol}`);
  return inst;
}

export const DEFAULT_SYMBOL = "EURUSD";

export const FEATURED_SYMBOLS = [
  "EURUSD",
  "XAUUSD",
  "BTCUSD",
  "US100",
  "GBPUSD",
  "USOIL",
] as const;
